# Generated by Django 4.1 on 2024-06-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("absence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absence",
            name="status",
            field=models.CharField(
                choices=[("0", "Absent"), ("1", "Présent"), ("2", "En retard")],
                max_length=1,
            ),
        ),
    ]
