# Generated by Django 4.1 on 2024-06-07 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0001_initial"),
        ("absence", "0002_alter_absence_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absence",
            name="status",
            field=models.CharField(
                choices=[("0", "Absent(e)"), ("1", "Présent(e)"), ("2", "En retard")],
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="ClassPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="class_photos/")),
                ("upload_date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.subject",
                    ),
                ),
            ],
        ),
    ]
