# Generated by Django 5.0.6 on 2024-06-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_alter_absence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('0', 'Absent(e)'), ('1', 'Présent(e)'), ('2', 'En retard')], max_length=1),
        ),
    ]
