# Generated by Django 4.1 on 2024-06-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profil", "0001_initial"),
        ("absence", "0003_alter_absence_status_classphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classphoto",
            name="photo",
            field=models.ImageField(upload_to="static/class_photos/"),
        ),
        migrations.CreateModel(
            name="Pin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="absence.classphoto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="profil.profil"
                    ),
                ),
            ],
        ),
    ]
