# Generated by Django 4.1 on 2024-06-10 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("absence", "0003_alter_absence_status"),
        ("absence", "0004_alter_classphoto_photo_pin"),
    ]

    operations = []
