# Generated by Django 5.0.6 on 2024-06-11 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("absence", "0005_merge_20240610_1051"),
        ("absence", "0005_merge_20240610_1053"),
    ]

    operations = []
