# Generated by Django 4.1 on 2024-06-11 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("absence", "0005_merge_20240610_1051"),
        ("absence", "0005_merge_20240610_1053"),
    ]

    operations = []
