# Generated by Django 5.0.6 on 2024-06-11 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("absence", "0006_merge_20240611_0946"),
        ("absence", "0006_merge_20240611_1112"),
    ]

    operations = []
