# Generated by Django 5.0.6 on 2024-06-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0005_merge_20240610_1428'),
        ('absence', '0007_merge_20240611_1408'),
    ]

    operations = [
    ]
