# Generated by Django 4.1 on 2024-06-11 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("absence", "0005_merge_20240610_1428"),
        ("absence", "0007_merge_20240611_1408"),
    ]

    operations = []
