# Generated by Django 5.0.6 on 2024-06-07 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='ue',
        ),
        migrations.AddField(
            model_name='subject',
            name='ue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='subjects.ue'),
            preserve_default=False,
        ),
    ]
